config/routes.rb
OFLunch::Application.routes.draw do

  resources :stats, only: %w{} do
    collection do
      get :popular_menus
    end
  end

  resources :menu_items, only: %w{index} do
    collection do
      get :today
    end
  end

  namespace :admin do

    resources :menu_items, only: %w{update}
    resources :vendors, only: %w{index create update destroy} do
      resources :menu_items, only: %w{index create destroy}
    end

    resources :balances, only: %w{index}
    resources :balance_logs, :only => %w{create}

    resources :meal_times, except: [:new, :show] do
      member do
        put :lock
        put :unlock
        put :close
      end
    end

  end

  resources :vendors, only: %w{index} do
    resources :menu_items, only: %w{index}
  end

  resources :messages, only: [] do
    member do
      put :redirect
      put :ignore
    end
  end

  resources :bills, only: [:index]

  resources :order_items, :only => [:index] do
    member do
      put :rating
      put :comment
    end
  end
  get 'order_items/:date' => 'order_items#index', as: 'date_order_items'

  resources :orders, only: %w{index new edit create update destroy} do
    collection do
      get :today
    end
  end

  devise_for :users

  resource :user, only: [:edit, :update] do
    get 'edit_password'
    put 'update_password'
  end

  resources :sessions, only: [:index] do
    collection do
      put :change
    end
  end

  root :to => 'orders#index'

end

app/models/message.rb
class Message < ActiveRecord::Base
  attr_accessible :content, :recipient_id, :entity
  belongs_to :recipient, class_name: 'User'
  belongs_to :entity, polymorphic: true

  def read!
    self.read = true
    self.save
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  before_filter :load_message

  def redirect
    @message.read!

    redirect_to params[:redirect_to]
  end

  def ignore
    # TODO, change this method to mark as read.
    @message.read!

    respond_to do |format|
      format.js { render 'ignore' }
    end
  end

  protected

  def load_message
    @message = Message.find params[:id]
  end
end

app/views/messages/_balance_log.html.erb
您的账户在
<span title="<%= l msg.created_at, format: :long %>">
  <i><%= time_ago_in_words msg.created_at %></i>
</span>
前充值
<%= msg.entity.amount %>元,
<%= link_to '点击查看', redirect_message_path(msg, redirect_to: bills_path), method: 'put' %>

app/views/messages/ignore.js.erb
$msg_item = $('#<%= dom_id(@message) %>');

if ($msg_item.parent().children().length == 1) {
  // if the message is the last one, remove notification count.
  $("#unread-message-count").remove();
  $('#unread-message-content').hide('drop', {direction: 'right'}, 270);
} else {
  $("#unread-message-count span").text(parseInt($("#unread-message-count").text()) - 1);
  $msg_item.remove();
}