config/routes.rb
OFLunch::Application.routes.draw do

  resources :stats, only: %w{} do
    collection do
      get :popular_menus
    end
  end

  resources :menu_items, only: %w{index} do
    collection do
      get :today
    end
  end

  namespace :admin do

    resources :menu_items, only: %w{update}
    resources :vendors, only: %w{index create update destroy} do
      resources :menu_items, only: %w{index create destroy}
    end

    resources :balances, only: %w{index}
    resources :balance_logs, :only => %w{create}

    resources :meal_times, except: [:new, :show] do
      member do
        put :lock
        put :unlock
        put :close
      end
    end

  end

  resources :vendors, only: %w{index} do
    resources :menu_items, only: %w{index}
  end

  resources :messages, only: [] do
    member do
      put :redirect
      put :ignore
    end
  end

  resources :bills, only: [:index]

  resources :order_items, :only => [:index] do
    member do
      put :rating
      put :comment
    end
  end
  get 'order_items/:date' => 'order_items#index', as: 'date_order_items'

  resources :orders, only: %w{index new edit create update destroy} do
    collection do
      get :today
    end
  end

  devise_for :users

  resource :user, only: [:edit, :update] do
    get 'edit_password'
    put 'update_password'
  end

  resources :sessions, only: [:index] do
    collection do
      put :change
    end
  end

  root :to => 'orders#index'

end

app/models/user.rb
# -*- encoding : utf-8 -*-
class User < ActiveRecord::Base
  devise :database_authenticatable, #:registerable,
    :rememberable, :trackable, :validatable

  has_many :orders
  has_many :unread_messages, foreign_key: 'recipient_id', class_name: 'Message', conditions: {read: false}, order: 'id DESC'
  has_one :balance, :dependent => :destroy

  scope :admin, where(role: 'admin')

  attr_accessible :email, :password, :password_confirmation, :remember_me, :name

  validates_presence_of :name

  after_create :create_balance_for_user

  def identifier
    self.name.presence || self.email
  end

  def admin?
    self.role == "admin"
  end

  def can_access_by?(user)
    user == self || user.admin?
  end

  def account_balance
    self.balance.amount
  end

  def today_order_items
    today_order = MealTime.today.orders.find_by_user_id(self.id)

    return [] if today_order.nil?

    today_order.order_items.includes(:menu_item).map do |order_item|
      {
        id: order_item.menu_item_id,
        name: order_item.menu_item.name,
        count: order_item.amount,
        price: order_item.menu_item.price,
      }
    end
  end

  protected

  def create_balance_for_user
    self.create_balance(amount: 0)
  end

end

app/controllers/users_controller.rb
# -*- encoding : utf-8 -*-

class UsersController < ApplicationController
  layout 'application'
  before_filter :load_current_user

  def edit
  end

  def edit_password
  end

  def update
    reject_other_fields_for_update
    if @user.update_attributes(params[:user])
      redirect_to edit_user_url, :notice => "修改成功"
    else
      render "edit"
    end
  end

  def update_password
    reject_other_fields_for_update_password
    if @user.update_with_password(params[:user])
      redirect_to edit_password_user_url, :notice => "修改成功"
    else
      render "edit_password"
    end
  end

  protected

  def load_current_user
    @user = current_user
  end

  def reject_other_fields_for_update
    params[:user].reject! { |k, v| not %w{name}.include?(k) }
  end

  def reject_other_fields_for_update_password
    params[:user].reject! { |k, v| not %w{current_password password password_confirmation}.include?(k) }
  end

end

app/views/users/_sidebar.html.erb
<ul class="nav nav-tabs nav-stacked">
	<li class="<%= action_name == 'edit' ? 'active' : '' %>"><%= link_to "个人信息", edit_user_path %></li>
	<li class="<%= action_name == 'edit_password' ? 'active' : '' %>"><%= link_to "修改密码", edit_password_user_path %></li>
</ul>

app/views/users/edit.html.erb
<div class="row">

  <div class="span2">
   <%= render "sidebar" %>
 </div>
 <div class="span10">

  <%= simple_form_for @user , :html => {:class => "form-horizontal"} do |f|%>
  <div class="inputs">
    <%= f.input :avatar, label: '&nbsp;' do %>
      <%= gravatar_image_tag @user.email, class: 'img-rounded' %>
      <br/>
      在<%= link_to 'Gravatar', 'https://en.gravatar.com/', target: '_blank' %>上修改你的头像
    <% end %>
  </div>
  <div class="inputs">
    <%= f.input :email, disabled: true %>
    <%= f.input :name, :placeholder => @user.name || "Name", :class => "input-small" %>
  </div>
  <div class="form-actions">
  	<%= f.submit "Update", :class => "btn btn-primary" %>
  </div>
  <%end%>
</div>

</div>

app/views/users/edit_password.html.erb
<div class="row">

	<div class="span2">
		<%= render "sidebar" %>   
	</div>
	<div class="span10">

		<%= simple_form_for @user, url: update_password_user_path, :html => {:class => "form-horizontal"} do |f|%>
		<div class="inputs">
			<%= f.input :current_password, :required => true %>
			<%= f.input :password, :autocomplete => "off", :required => true, label: '新密码' %>
			<%= f.input :password_confirmation, :required => true %>
		</div>
		<div class="form-actions">
			<%= f.button :submit, "Update", class: "btn-primary" %>
		</div>
		<%end%>
	</div>

</div>