config/routes.rb
OFLunch::Application.routes.draw do

  resources :stats, only: %w{} do
    collection do
      get :popular_menus
    end
  end

  resources :menu_items, only: %w{index} do
    collection do
      get :today
    end
  end

  namespace :admin do

    resources :menu_items, only: %w{update}
    resources :vendors, only: %w{index create update destroy} do
      resources :menu_items, only: %w{index create destroy}
    end

    resources :balances, only: %w{index}
    resources :balance_logs, :only => %w{create}

    resources :meal_times, except: [:new, :show] do
      member do
        put :lock
        put :unlock
        put :close
      end
    end

  end

  resources :vendors, only: %w{index} do
    resources :menu_items, only: %w{index}
  end

  resources :messages, only: [] do
    member do
      put :redirect
      put :ignore
    end
  end

  resources :bills, only: [:index]

  resources :order_items, :only => [:index] do
    member do
      put :rating
      put :comment
    end
  end
  get 'order_items/:date' => 'order_items#index', as: 'date_order_items'

  resources :orders, only: %w{index new edit create update destroy} do
    collection do
      get :today
    end
  end

  devise_for :users

  resource :user, only: [:edit, :update] do
    get 'edit_password'
    put 'update_password'
  end

  resources :sessions, only: [:index] do
    collection do
      put :change
    end
  end

  root :to => 'orders#index'

end

app/models/vendor.rb
# -*- encoding : utf-8 -*-
class Vendor < ActiveRecord::Base
  acts_as_paranoid

  has_many :menu_items

  validates_presence_of :name

  def menu_items_order_by_popular
    self.menu_items.joins("LEFT JOIN order_items ON menu_items.id = order_items.menu_item_id").group('menu_items.id').order('SUM(amount) DESC')
  end

  # return categories which belongs a certain vendor
  # format: {
  #   <Category> => [<MenuItem>, <MenuItem>]
  # }
  def categories_with_menu_items
    result = {}
    self.menu_items.includes(:category).each do |menu_item|
      result[menu_item.category.name] ||= {}
      result[menu_item.category.name]['category_name'] = menu_item.category.name
      result[menu_item.category.name]['menu_items'] ||= []
      result[menu_item.category.name]['menu_items'] << menu_item
    end
    result
  end
end

app/controllers/admin/vendors_controller.rb
# -*- encoding : utf-8 -*-
class Admin::VendorsController < Admin::BaseController
  set_tab :vendors

  def index
    @vendors = Vendor.all
    @vendor = Vendor.new
    @meal_time = MealTime.opened

    respond_to do |format|
      format.html
    end
  end

  def create
    @vendor = Vendor.new(params[:vendor])

    respond_to do |format|
      if @vendor.save
        format.js
      else
        format.js { render 'new' }
      end
    end
  end

  def update
    @vendor = Vendor.find(params[:id])

    respond_to do |format|
      if @vendor.update_attributes(params[:vendor])
        format.json { head :no_content }
      else
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @vendor = Vendor.find(params[:id])

    respond_to do |format|
      if MealTime.opened.try(:activated?) or MealTime.opened.try(:locked?)
        format.js { render js: "用户正在订餐中，无法删除商家#{@vendor.name}" }
      else
        @vendor.destroy
        format.js
      end
    end
  end
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  set_tab :vendor_list
  
  def index
    @vendors = Vendor.all
  end
end

app/views/vendors/_modal_form.html.erb
  <%= simple_form_for(@vendor, remote: true, html: {class: 'form-horizontal'}) do |f| %>

  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">×</button>
    <h3>添加商家</h3>
  </div>

  <div class="modal-body">
    <%= f.error_notification %>
    <div class="form-inputs">
      <%= f.input :name %>
    </div>
  </div>

  <div class="modal-footer">
    <%= f.button :submit, t('confirm'), class: 'btn btn-primary' %>
  </div>

  <% end %>

app/views/vendors/index.html.erb
<div class="row">

  <div class="span2">
    <ul class="nav nav-pills nav-stacked" id="vendors_nav">
      <% @vendors.each do |vendor| %>
      <li><%= link_to vendor.name, vendor_menu_items_path(vendor), remote: true %></li>
      <% end %>
    </ul>
    <span>&nbsp;</span>
  </div>

  <div class="span6">
    <div id="menu_items">
      Click on left links to see more.
    </div>
  </div>
</div>

<%= content_for :footer do %>
<script type="text/javascript">

  $body = $('body');
  $body.on('click', '#vendors_nav li', function() {
    $("#vendors_nav li.active").removeClass('active');
    $(this).addClass('active');
  });
  $(window).scroll(function() {
    if ($(window).scrollTop() > 0) {
      $("#vendors_nav").attr("style", "position: fixed;width:" + $('.span2').width() + "px");
    } else {
      $("#vendors_nav").attr("style", "");
    }
  });

  $("#vendors_nav li").first().find('a').click();

</script>
<% end %>