config/routes.rb
OFLunch::Application.routes.draw do

  resources :stats, only: %w{} do
    collection do
      get :popular_menus
    end
  end

  resources :menu_items, only: %w{index} do
    collection do
      get :today
    end
  end

  namespace :admin do

    resources :menu_items, only: %w{update}
    resources :vendors, only: %w{index create update destroy} do
      resources :menu_items, only: %w{index create destroy}
    end

    resources :balances, only: %w{index}
    resources :balance_logs, :only => %w{create}

    resources :meal_times, except: [:new, :show] do
      member do
        put :lock
        put :unlock
        put :close
      end
    end

  end

  resources :vendors, only: %w{index} do
    resources :menu_items, only: %w{index}
  end

  resources :messages, only: [] do
    member do
      put :redirect
      put :ignore
    end
  end

  resources :bills, only: [:index]

  resources :order_items, :only => [:index] do
    member do
      put :rating
      put :comment
    end
  end
  get 'order_items/:date' => 'order_items#index', as: 'date_order_items'

  resources :orders, only: %w{index new edit create update destroy} do
    collection do
      get :today
    end
  end

  devise_for :users

  resource :user, only: [:edit, :update] do
    get 'edit_password'
    put 'update_password'
  end

  resources :sessions, only: [:index] do
    collection do
      put :change
    end
  end

  root :to => 'orders#index'

end

app/models/vendor.rb
# -*- encoding : utf-8 -*-
class Vendor < ActiveRecord::Base
  acts_as_paranoid

  has_many :menu_items

  validates_presence_of :name

  def menu_items_order_by_popular
    self.menu_items.joins("LEFT JOIN order_items ON menu_items.id = order_items.menu_item_id").group('menu_items.id').order('SUM(amount) DESC')
  end

  # return categories which belongs a certain vendor
  # format: {
  #   <Category> => [<MenuItem>, <MenuItem>]
  # }
  def categories_with_menu_items
    result = {}
    self.menu_items.includes(:category).each do |menu_item|
      result[menu_item.category.name] ||= {}
      result[menu_item.category.name]['category_name'] = menu_item.category.name
      result[menu_item.category.name]['menu_items'] ||= []
      result[menu_item.category.name]['menu_items'] << menu_item
    end
    result
  end
end

app/controllers/admin/vendors_controller.rb
# -*- encoding : utf-8 -*-
class Admin::VendorsController < Admin::BaseController
  set_tab :vendors

  def index
    @vendors = Vendor.all
    @vendor = Vendor.new
    @meal_time = MealTime.opened

    respond_to do |format|
      format.html
    end
  end

  def create
    @vendor = Vendor.new(params[:vendor])

    respond_to do |format|
      if @vendor.save
        format.js
      else
        format.js { render 'new' }
      end
    end
  end

  def update
    @vendor = Vendor.find(params[:id])

    respond_to do |format|
      if @vendor.update_attributes(params[:vendor])
        format.json { head :no_content }
      else
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @vendor = Vendor.find(params[:id])

    respond_to do |format|
      if MealTime.opened.try(:activated?) or MealTime.opened.try(:locked?)
        format.js { render js: "用户正在订餐中，无法删除商家#{@vendor.name}" }
      else
        @vendor.destroy
        format.js
      end
    end
  end
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  set_tab :vendor_list
  
  def index
    @vendors = Vendor.all
  end
end

app/views/admin/vendors/_modal_form.html.erb
  <%= simple_form_for([:admin, @vendor], remote: true, html: {class: 'form-horizontal'}) do |f| %>

  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">×</button>
    <h3>添加商家</h3>
  </div>

  <div class="modal-body">
    <%= f.error_notification %>
    <div class="form-inputs">
      <%= f.input :name, autofocus: true %>
    </div>
  </div>

  <div class="modal-footer">
    <%= f.button :submit, t('confirm'), class: 'btn btn-primary' %>
  </div>

  <% end %>

app/views/admin/vendors/_tr_vendor.html.erb
<tr id="tr_<%= dom_id(vendor) %>">
  <td width="50%"><%= best_in_place vendor, :name, path: [:admin, vendor] %></td>
  <td>
    <%= link_to '菜单', admin_vendor_menu_items_path(vendor), remote: true %>
    <% if @meal_time.nil? or @meal_time.closed? %>
      <%= link_to '删除', [:admin, vendor], data: {confirm: "你确定要删除 #{vendor.name} 吗？"}, method: :delete, remote: true %>
    <% end %>
  </td>
</tr>

app/views/admin/vendors/create.js.erb
$("#vendors_table").append("<%= escape_javascript(render(partial: 'tr_vendor', locals: {vendor: @vendor})) %>");

$("#modal_form").modal('hide');

// reset form
<% @vendor = Vendor.new %>
$("#modal_form").html("<%= escape_javascript(render(partial: 'modal_form')) %>");

jQuery('.best_in_place').best_in_place();

app/views/admin/vendors/destroy.js.erb
$("#tr_<%= dom_id(@vendor) %>").remove();

$menu_items_div = $('#menu_items_div');
if ($menu_items_div.data('vendor_id') == "<%= dom_id(@vendor) %>") {
    $menu_items_div.empty();
};

app/views/admin/vendors/index.html.erb
<div class="row">
  <div class="span4">
    <h2>商家列表</h2>

    <table class="table table-striped table-bordered" id="vendors_table">
      <tr>
        <th>商家名称</th>
        <th>操作</th>
      </tr>

      <%= render partial: "tr_vendor", collection: @vendors, as: :vendor %>
    </table>

    <a class="btn" data-toggle="modal" href="#modal_form" >
      <i class="icon-plus-sign"></i>
      添加
    </a>

    <div class="modal hide" id="modal_form">
      <%= render "modal_form" %>
    </div>
  </div>

  <div class="span8" id="menu_items_div"></div>
</div>

app/views/admin/vendors/new.js.erb
$("#modal_form").html("<%= escape_javascript(render(partial: 'modal_form')) %>");